MLK-16212 mmc: fsl_esdhc: fix build issue
Fix the following build issue:
"
 In function ‘esdhc_set_ios’:
 warning: unused variable ‘ret’ [-Wunused-variable]
 int ret;
 ^~~
 At top level:
 warning: ‘usdhc_imx8qm_data’ defined but not used [-Wunused-variable]
 static struct esdhc_soc_data usdhc_imx8qm_data = {
		                               ^~~~~~~~~~~~~~~~~
To qxp nand boot defconfig:
 error: ‘esdhc_set_vdd’ undeclared here (not in a function)
 .set_vdd = esdhc_set_vdd,
               ^~~~~~~~~~~~~
"

Signed-off-by: Peng Fan <peng.fan@nxp.com>
(cherry picked from commit b899394e29c6446208be2bef664b010eab370e23)