configs: ls1012a/ls1046a: Define CONFIG_ENV_OVERWRITE
CONFIG_ENV_OVERWRITE disable write protection on various environment
variables like "ethaddr" and "serial".

Define the config in LS1046A and LS1012A common header as both of them
require this entry. Also, resolve an error while setting multiple values
of "ethaddr" variable.

Before the change:
=> setenv ethaddr 00:E0:0C:00:06:0
=> setenv ethaddr 00:E0:0C:00:06:1
Error: Can't overwrite "ethaddr"
Error inserting "ethaddr" variable, errno=1

After the change:
=> setenv ethaddr 00:E0:0C:00:06:0
=> setenv ethaddr 00:E0:0C:00:06:1

Signed-off-by: Kuldeep Singh <kuldeep.singh@nxp.com>