MLK-14636 Tools: Add python lib dependency check for libfdt
The tools/makefile will build a libfdt Python module if swig is available.
But actually it not only need swig but also need python libary. We will get
build break below when python is not installed. It is better to add more
check for python lib.

Because applications may install some python libs, but not the full libpython-dev,
then the Python.h is missed. We check Python.h to instead checking libs.

tools/libfdt_wrap.c:147:21: fatal error: Python.h: No such file or directory

Signed-off-by: Ye Li <ye.li@nxp.com>