MA-17570 Show unlock warning logo before AVB sevice is closed
The unlock warning logo show will query the device lock status
via AVB tipc (if trusty is enabled). Show the unlock warning
logo before AVB tipc channel is closed, this will fix below
warning:
  avb.c:90: ERROR avb_do_tipc: AVB TIPC client not initialized

Test: boots with trusty.

Signed-off-by: Ji Luo <ji.luo@nxp.com>
Change-Id: I9fa675b72193d7d618ddf2d0d813b97a3073bfea
(cherry picked from commit 7e74dff704acba6390906e016c8a973d1ea5bd2f)