ENGR00289247 Fix build break for mx6qsabresd
Fix build break as follows.

make ARCH=arm CROSS_COMPILE=arm-linux-gnueabi- mx6qsabresd

mx6qsabresd.c:189: error: ‘MX6_PAD_EIM_A16__EPDC_SDDO_0’ undeclared here (not in a function)
mx6qsabresd.c:190: error: ‘MX6_PAD_EIM_DA10__EPDC_SDDO_1’ undeclared here (not in a function)
mx6qsabresd.c:191: error: ‘MX6_PAD_EIM_DA12__EPDC_SDDO_2’ undeclared here (not in a function)
mx6qsabresd.c:192: error: ‘MX6_PAD_EIM_DA11__EPDC_SDDO_3’ undeclared here (not in a function)
mx6qsabresd.c:193: error: ‘MX6_PAD_EIM_LBA__EPDC_SDDO_4’ undeclared here (not in a function)
mx6qsabresd.c:194: error: ‘MX6_PAD_EIM_EB2__EPDC_SDDO_5’ undeclared here (not in a function)
mx6qsabresd.c:195: error: ‘MX6_PAD_EIM_CS0__EPDC_SDDO_6’ undeclared here (not in a function)
mx6qsabresd.c:196: error: ‘MX6_PAD_EIM_RW__EPDC_SDDO_7’ undeclared here (not in a function)
mx6qsabresd.c:197: error: ‘MX6_PAD_EIM_A21__EPDC_GDCLK’ undeclared here (not in a function)
mx6qsabresd.c:198: error: ‘MX6_PAD_EIM_A22__EPDC_GDSP’ undeclared here (not in a function)
mx6qsabresd.c:199: error: ‘MX6_PAD_EIM_A23__EPDC_GDOE’ undeclared here (not in a function)
mx6qsabresd.c:200: error: ‘MX6_PAD_EIM_A24__EPDC_GDRL’ undeclared here (not in a function)
mx6qsabresd.c:201: error: ‘MX6_PAD_EIM_D31__EPDC_SDCLK’ undeclared here (not in a function)
mx6qsabresd.c:202: error: ‘MX6_PAD_EIM_D27__EPDC_SDOE’ undeclared here (not in a function)
mx6qsabresd.c:203: error: ‘MX6_PAD_EIM_DA1__EPDC_SDLE’ undeclared here (not in a function)
mx6qsabresd.c:204: error: ‘MX6_PAD_EIM_EB1__EPDC_SDSHR’ undeclared here (not in a function)
mx6qsabresd.c:205: error: ‘MX6_PAD_EIM_DA2__EPDC_BDR_0’ undeclared here (not in a function)
mx6qsabresd.c:206: error: ‘MX6_PAD_EIM_DA4__EPDC_SDCE_0’ undeclared here (not in a function)
mx6qsabresd.c:207: error: ‘MX6_PAD_EIM_DA5__EPDC_SDCE_1’ undeclared here (not in a function)
mx6qsabresd.c:208: error: ‘MX6_PAD_EIM_DA6__EPDC_SDCE_2’ undeclared here (not in a function)

Signed-off-by: Robby Cai <R63905@freescale.com>
(cherry picked from commit 6c49efa816bdb4f3c9de8b3df12641989bfaa1a9)