PCI: layerscape: Fix build errors on LS1021A platforms
Fix the following build errors:
drivers/pci/pcie_layerscape.c: In function ‘ls_pcie_probe’:
drivers/pci/pcie_layerscape.c:586:13: error: ‘SVR_LX2160A’ undeclared (first use in this function)
  586 |  if (svr == SVR_LX2160A)
      |             ^~~~~~~~~~~
drivers/pci/pcie_layerscape.c:586:13: note: each undeclared identifier is reported only once for each function it appears in
drivers/pci/pcie_layerscape.c:591:13: error: ‘SVR_LS2080A’ undeclared (first use in this function); did you mean ‘SVR_LS2088A’?
  591 |  if (svr == SVR_LS2080A || svr == SVR_LS2085A)
      |             ^~~~~~~~~~~
      |             SVR_LS2088A
drivers/pci/pcie_layerscape.c:591:35: error: ‘SVR_LS2085A’ undeclared (first use in this function); did you mean ‘SVR_LS2088A’?
  591 |  if (svr == SVR_LS2080A || svr == SVR_LS2085A)
      |                                   ^~~~~~~~~~~
      |                                   SVR_LS2088A

Fixes: 7c6a45e9efa3 ("PCI: layerscape: Add the PCIe EP mode support for lx2160a-v2")
Fixes: 98a564f35ef8 ("PCI: layerscape: Add the configuration for PF1 and VFs")
Signed-off-by: Hou Zhiqiang <Zhiqiang.Hou@nxp.com>