MA-12216 [Android] Fix u-boot build errors
Type mismatch will cause some build warnings and they will be treated
as errors when '-Werror' is specified. Fix the error logs loke below:
  error: cast from pointer to integer of different size
  [-Werror=pointer-to-int-cast]

Test: build pass for evk_imx8mm

Change-Id: I48489815c8310c659a5c7c860433c4a93cb0dc66
Signed-off-by: Luo Ji <ji.luo@nxp.com>