MA-10557 [Android] enlarge malloc size
uboot will have below error log when verify boot.img
avb_util.c:199: ERROR: Failed to allocate memory.

the default size of malloc is 36M. But we need to load boot.img
with malloc addr. enlarge the size of malloc to 64M.

Change-Id: I64d0403b0cc970128cdfd1eafe7a4680a92f7c25
Signed-off-by: zhang sanshan <sanshan.zhang@nxp.com>