LFU-406 mx6ul/mx6ulz: Fix build break caused by RNG patch
Fix build break of issue "undefined reference to `dm_rng_read'" on
6UL and 6ULZ. which is introduced by commit 8789f3c
(PLATSEC-1781-2 MX6: Device tree fix-up)

Signed-off-by: Ye Li <ye.li@nxp.com>
Reviewed-by: Kshitiz Varshney <kshitiz.varshney@nxp.com>