ENGR00224313:i.MX6 general:enable CONFIG_CMD_IMXOTP to fix the build error
Commit 7942886(ENGR00221503-2 imx6: add cpu serial number support)
introduces dependency on "CONFIG_SERIAL_TAG" and "CONFIG_CMD_IMXOTP".
On U-boot configuration header files which only defines the first one, build
error will be met.

--- build error message ---
arm_cortexa8/mx6/libmx6.a(generic.o): In function `get_board_serial':
arm_cortexa8/mx6/generic.c:1438: undefined reference to `imx_otp_read_one_u32'
arm_cortexa8/mx6/generic.c:1439: undefined reference to `imx_otp_read_one_u32'
---------------------------

To fix it, add missing "CONFIG_CMD_IMXOTP" macro definition in the
config head file.

Configs affected are:
---------------------------
	mx6q_arm2_iram
	mx6q_sabresd_iram
	mx6dl_arm2_iram
	mx6sl_arm2_iram
	mx6sl_evk_iram

Signed-off-by: Eric Sun <jian.sun@freescale.com>